### PR TITLE
Reading addition and a Question

### PR DESCRIPTION
**Pull request by hubertogitero**
Added the much more common reading of 'months and years'. Don't know if you allow these type of changes?
Uncertain about the formating on this, sorry. Maybe one should remove the parenthesis?

### CODE REVIEW

**Comment by hubertogitero** [comment]
Technically there's a small difference between the readings in formality (from what I understand), so maybe it's inappropriate to add the more common reading?

**Review by SethClydesdale — APPROVED** [review]
Hello @hubertogitero!

From my understanding, when there's more than one reading for a word, *on* readings are usually used in more formal settings compared to *kun* readings which feel less formal. In this lesson, the reading material has a more formal tone which is most likely why ねんげつ is used over としつき. Regardless, I'm not against adding the kun reading since it's always good to know both.

**Comment by hubertogitero** [comment]
Thanks for the clarification, that was my impression as well!

I must have formatted the change incorrectly however because now the entry is marked "correct" when doing the "Write the Definition" exercise type even if you enter nothing in the field.

**Comment by SethClydesdale** [comment]
Thanks for letting me know. It should be fixed now! For separating multiple readings, it looks like I used the full-width ／ over the half-width /.

**Pull request merged**
